MVCBase/Controllers/Bup/ProyectosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.WebSockets;
using CrystalDecisions.Shared;
using MVCBase;
using MVCBase.Models;

namespace MVCBase.Controllers
{
    public class ProyectosController : Controller
    {
        private MODERNIZACION_DBEntities db = new MODERNIZACION_DBEntities();

        // GET: Proyectos
        public ActionResult Index()
        {
            return View(db.cxmProyectos.ToList());
        }

        // GET: Proyectos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cxmProyectos cxmProyectos = db.cxmProyectos.Find(id);
            if (cxmProyectos == null)
            {
                return HttpNotFound();
            }
            return View(cxmProyectos);
        }

        // GET: Proyectos/Details/5
        public ActionResult Preview(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cxmProyectos proy = db.cxmProyectos.Find(id);                  
            if (proy == null)
            {
                return HttpNotFound();
            }
            List<CuentasPorFranjaViewModel> cuentas = new List<CuentasPorFranjaViewModel>();
            foreach (var cxmFranja in proy.cxmFranja)
            {                                                                   
                var factorConversion = (proy.montoEjecutado * cxmFranja.porcentaje / 100) / GetAreaTotal(proy);
                foreach (var inmueble in cxmFranja.cxmInmueblesPorProyecto)
                    cuentas.Add(PerformCalculos(CreateCuenta(inmueble), proy, factorConversion));
            }
            ViewBag.cuentas = cuentas;
            ViewBag.idFactorSocioEconomico = new SelectList(db.FactorSocioEconomico, "idFactorSocioEconomico", "factorSocioEconomico1");
            ViewBag.idFactorUso = new SelectList(db.FactorUso, "idFactorUso", "factorUso1");
            ViewBag.idFactorArea = new SelectList(db.FactorArea, "idFactorArea", "value");
            ViewBag.idAccesoAjuste = new SelectList(db.AccesoAjuste, "idAccesoAjuste", "value");
            ViewBag.idFactorDistancia = new SelectList(db.FactorDistancia, "idFactorDistancia", "value");           
            ViewBag.idFranja = new SelectList(db.cxmFranja.Where(x => x.idProyecto == proy.idProyecto), "idFranja", "numFranja");
            ViewBag.franjas = ViewBag.idFranja;
            ViewBag.factores = new SelectList(new [] { "Factor Área", "Factor Socioeconómico", "Acceso Ajuste", "Factor Distancia", "Factor Uso" }.Select((f, index) => 
                new { Text = f, Value = index.ToString() }), "Value", "Text");
            ViewBag.valores = new SelectList(db.FactorArea, "idFactorArea", "value");
            ViewBag.errorMessage = TempData["errorMessage"];
            ViewBag.added = TempData["added"];
            this.ControllerContext.HttpContext.Response.Headers.Add("Access-Control-Allow-Origin", "*");
            return View(proy);
        }

        public ActionResult ValoresPerFactor(int factor)
        {
            if (factor == 0) ViewBag.valores = new SelectList(db.FactorArea, "idFactorArea", "value");
            if (factor == 1) ViewBag.valores = new SelectList(db.FactorSocioEconomico, "idFactorSocioEconomico", "value");
            if (factor == 2) ViewBag.valores = new SelectList(db.AccesoAjuste, "idAccesoAjuste", "value");
            if (factor == 3) ViewBag.valores = new SelectList(db.FactorDistancia, "idFactorDistancia", "value");
            if (factor == 4) ViewBag.valores = new SelectList(db.FactorUso, "idFactorUso", "value");
            return PartialView();
        }
        
        public ActionResult InsertCatCca(cxmInmueblesPorProyecto inmueblexProyecto, int idProyecto)//int idProyecto, int franja, string cuenta, int factorArea, int factorSocioEconomico, int accesoAjuste, int factorUso, int factorDistancia)
        {
            var inmueble = db.consultaInmuebles.FirstOrDefault(x => x.CatCca == inmueblexProyecto.catCca.Replace("-", ""));
            if (inmueble != null)
            {                
                inmueblexProyecto.fecha = DateTime.Now;
                var existe = 
                    db.cxmInmueblesPorProyecto.FirstOrDefault(
                        x => x.cxmFranja.idProyecto == idProyecto && x.catCca == inmueblexProyecto.catCca);
                if (existe == null)
                {
                    db.cxmInmueblesPorProyecto.Add(inmueblexProyecto);
                    db.SaveChanges();
                    TempData["added"] = "YES";
                } else TempData["errorMessage"] = "El inmueble ya fue registrado en este proyecto.";
            } else TempData["errorMessage"] = "El inmueble fue escrito incorrectamente o no existe en la base de datos.";
            return RedirectToAction("Preview", new { id = idProyecto });
        }

        public ActionResult UpdateFranja(int franjas, int factores, int valores, int idProyecto)
        {
            var franja = db.cxmFranja.FirstOrDefault(x => x.idFranja == franjas);
            foreach (var inmueble in franja.cxmInmueblesPorProyecto)
            {
                if (factores == 0) inmueble.idFactorArea = valores;
                if (factores == 1) inmueble.idFactorSocioEconomico = valores;
                if (factores == 2) inmueble.idAccesoAjuste = valores;
                if (factores == 3) inmueble.idFactorDistancia = valores;
                if (factores == 4) inmueble.idFactorUso = valores;
                db.Entry(inmueble).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Preview", new { id = idProyecto });
        }

        private decimal GetAreaFranja(int idFranja)
        {
            var franja = db.cxmFranja.FirstOrDefault(x => x.idFranja == idFranja);
            List<consultaInmuebles> cInmueblesList = new List<consultaInmuebles>();
            if (franja != null)
            {
                var inmuebles = franja.cxmInmueblesPorProyecto;
                decimal areasReales = 0;                
                foreach (var inmueble in inmuebles)
                {
                    var consultaInmueble = db.consultaInmuebles.FirstOrDefault(x => x.CatCca == inmueble.catCca.Replace("-", "").Replace(" ", ""));
                    cInmueblesList.Add(consultaInmueble);
                    if (consultaInmueble?.CatAre!= null) areasReales += (decimal)consultaInmueble.CatAre;
                    if (consultaInmueble == null || consultaInmueble.CatAre == null || consultaInmueble.CatAre == 0)
                    {
                        int a = 0;
                    }
                }
                ViewBag.cInmueblesList = cInmueblesList;
                return areasReales;
            }            
            return 0;
        }

        private decimal GetAreaTotal(cxmProyectos proy)
        {
            //List<consultaInmuebles> cInmueblesList = new List<consultaInmuebles>();
            if (proy != null)
            {
                var inmuebles = new List<cxmInmueblesPorProyecto>();
                foreach (var franja in proy.cxmFranja) inmuebles.AddRange(franja.cxmInmueblesPorProyecto);           
                decimal areasReales = 0;
                foreach (var inmueble in inmuebles)
                {
                    //var consultaInmueble = db.consultaInmuebles.FirstOrDefault(x => x.CatCca == inmueble.catCca.Replace("-", "").Replace(" ", ""));
                    //cInmueblesList.Add(consultaInmueble);
                    areasReales += ((decimal)inmueble.area == null) ? 0 : (decimal)inmueble.area;
                    if (inmueble == null || inmueble.area == null || inmueble.area == 0)
                    {
                        int a = 0;
                    }
                }
                //ViewBag.cInmueblesList = cInmueblesList;
                return areasReales;
            }
            return 0;
        }

        private CuentasPorFranjaViewModel CreateCuenta(cxmInmueblesPorProyecto inmueble)
        {
            var cInmueblesList = ViewBag.cInmueblesList as List<consultaInmuebles>;
            //var area = cInmueblesList.FirstOrDefault(x => x.CatCca.Replace(" ", "") == inmueble.catCca.Replace("-", "").Replace(" ", ""))?.CatAre;
            //var beforeViewModel = SetErrorsBeforeViewModelCreation(inmueble, (decimal)area);
            //if (beforeViewModel == null)
                return new CuentasPorFranjaViewModel()
            {
                IdInmueblePorProyecto = inmueble.idInmueblePorProyecto,
                NumFranja = inmueble.cxmFranja.numFranja,
                CatCca = inmueble.catCca,
                AreaTerreno = inmueble.area,
                FactorDistancia = ((inmueble.idFactorDistancia == null) ? null : inmueble.FactorDistancia.value),
                FactorArea = ((inmueble.idFactorArea == null) ? null : inmueble.FactorArea.value),
                FactorUso = ((inmueble.idFactorUso == null) ? null : inmueble.FactorUso?.value),
                SocioEconomico = ((inmueble.idFactorSocioEconomico == null) ? null : inmueble.FactorSocioEconomico.value),
                AccesoAjuste = ((inmueble.idAccesoAjuste == null) ? null : inmueble.AccesoAjuste.value)
            };
            //return beforeViewModel;
        }

        private CuentasPorFranjaViewModel SetErrorsBeforeViewModelCreation(cxmInmueblesPorProyecto inmueble, decimal area)
        {
            if (inmueble.idFactorDistancia == null || inmueble.idFactorArea == null ||inmueble.idFactorUso == null ||
                inmueble.idFactorSocioEconomico == null || inmueble.idAccesoAjuste == null)

MVCBase/Views/Proyectos/CreateProyectoExcel.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Carga de Archivos</h2>

@using (Html.BeginForm("UploadFile", "Proyectos", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Migración de Excel a Base de Datos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="contentpanel">
            <div class="mb15"></div>
            <div class="row">
                <div class="col-md-10">
                    @*<h4 class="panel-title mb5">Emphasize Step Wizard</h4>
                    <p class="mb15">An emphasized step style wizard that is perfect for e-commerce websites.</p>*@

                    

                        

                        @*<div id="wizard-basic2" class="wizard-style2 wizard clearfix" role="application">
                            <div class="steps clearfix">
                                <ul role="tablist"><li role="tab" class="first done" aria-disabled="false" aria-selected="false"><a id="wizard-basic2-t-0" href="#wizard-basic2-h-0" aria-controls="wizard-basic2-p-0"><span class="number">1.</span> Personal Details <small>Enter your personal information.</small></a></li><li role="tab" class="done" aria-disabled="false" aria-selected="false"><a id="wizard-basic2-t-1" href="#wizard-basic2-h-1" aria-controls="wizard-basic2-p-1"><span class="number">2.</span> Shipping Details <small>Choose your shipping options.</small></a></li><li role="tab" class="last current" aria-disabled="false" aria-selected="true"><a id="wizard-basic2-t-2" href="#wizard-basic2-h-2" aria-controls="wizard-basic2-p-2"><span class="current-info audible">current step: </span><span class="number">3.</span> Payment Details <small>Enter your card information.</small></a></li></ul>
                            </div>
                            <div class="content clearfix">
                                <h3 id="wizard-basic2-h-0" tabindex="-1" class="title">
                                    Carga de Archivo <small>Suba el archivo de Excel.</small>
                                </h3>
                                <div id="wizard-basic2-p-0" role="tabpanel" aria-labelledby="wizard-basic2-h-0" class="body" aria-hidden="true" style="left: -904px; display: none;">
                                    <div class="col-md-4">
                                        <label class="col-md-2" for="file[0]">Archivo</label>
                                        <input type="file" class="form-control input col-md-4" name="file[0]" id="file[0]" />
                                    </div>
                                </div>
                                <h3 id="wizard-basic2-h-1" tabindex="-1" class="title">
                                    Shipping Details <small>Choose your shipping options.</small>
                                </h3>
                                <div id="wizard-basic2-p-1" role="tabpanel" aria-labelledby="wizard-basic2-h-1" class="body" aria-hidden="true" style="display: none; left: -904px;">
                                    <p>Wonderful transition effects.</p>
                                </div>
                                <h3 id="wizard-basic2-h-2" tabindex="-1" class="title current">
                                    Payment Details <small>Enter your card information.</small>
                                </h3>
                                <div id="wizard-basic2-p-2" role="tabpanel" aria-labelledby="wizard-basic2-h-2" class="body current" aria-hidden="false" style="display: block; left: 0px;">
                                    <p>The next and previous buttons help you to navigate through your content.</p>
                                </div>
                            </div>
                            <div class="actions clearfix">
                                <ul role="menu" aria-label="Pagination"><li class="" aria-disabled="false"><a href="#previous" role="menuitem">Previous</a></li><li aria-hidden="true" aria-disabled="true" class="disabled" style="display: none;"><a href="#next" role="menuitem">Next</a></li><li aria-hidden="false" style="display: block;"><a href="#finish" role="menuitem">Finish</a></li></ul>
                            </div>
                        </div>*@
           
                </div>
            </div>
        </div>
        <div class="col-md-12">
        <div class="panel panel-inverse" id="wid-id-5" data-currentnbr="0" data-currentfranja="0">        
                <div class="panel-heading">
                    <h3 class="panel-title">Subida de Archivo</h3>
                </div>
                <div class="panel-body" style="padding-left: 2px; padding-right: 2px;">
                    <div class="row">

                        <div class="col-md-12" style="margin-top: 1%">
                            <div class="col-md-2">
                                <label class="col-md-2" for="file">Archivo</label>
                                <input type="file" onchange="GetDefaultValuesForFile(this.value)" class="form-control input col-md-4" name="file" id="file"/>
                            </div>
                            <div class="col-md-2">
                                <label class="col-md-12" for="file">Fila Inicial</label>
                                <input type="number" min="0" class="form-control input col-md-12" name="filainicial" id="filaInicial"/>
                            </div>
                            <div class="col-md-2">
                                <label class="col-md-12" for="file">No. de Columnas</label>
                                <input type="number" min="0" class="form-control input col-md-12" name="columnas" id="columnas"/>
                            </div>
                            <div class="col-md-3">
                                <label class="col-md-12" for="file">Databases</label>
                                @Html.DropDownList("databases", (ViewBag.databases as SelectList),
                               new { @class = "form-control input col-md-12", id = "selecteddb",
                                   onchange = "getdbtables()"
                               })
                            </div>
                            <div class="col-md-3" id="tablesDiv">
                                <label class="col-md-12" for="file">Tablas</label>
                                <Select class="form-control input col-md-12"></Select>
                            </div>
                        </div>                        

                    </div>
                </div>
                <div class="panel-footer">
                    <input type="submit" class="btn btn-primary" value="Subir" />
                </div>
            </div><!-- panel -->
        </div><!-- col-sm-6 -->
    </div>

}

<script type="text/javascript">

        function showMessage(message, color) {
            $.gritter.add({
                title: "Municipalidad de San Pedro Sula",
                text: message,
                class_name: "with-icon exclamation-circle warning"
            });
        }


document.addEventListener('DOMContentLoaded', function () {

  'use strict';
    
  $('#wizard-basic2').steps({    
    headerTag: 'h3',
    bodyTag: 'div',
    transitionEffect: 'slideLeft',
    autoFocus: true
  });

    

});

function GetDefaultValuesForFile(value) {
    $.ajax({
        method: "POST",
        datatype: "json",
        async: false,
        url: "/Proyectos/GetDefaultValuesForFile",
        data: { file: value }
    }).success(function (data) {
        if (data != "NOTFOUND") {
            $('#filaInicial').val(data.NumFila);
            $('#columnas').val(data.NumColumns);
            $('#selecteddb').val(data.IdDbInstance);
            getdbtables();
        }        
    }).fail(function(data) {
        if (data == "") {
            
        }
    });    
    //getTableIndex();
}

function getdbtables() {
    var selecteddb = $('#selecteddb').val();
    $.ajax({
        method: "POST",
        datatype: "json",
        async: false,
        url: "/Proyectos/GetDBTables",
        data: { selecteddb: selecteddb }
    }).success(function (data) {
        $('#tablesDiv').html(data);
    });
}

function getTableIndex() {
    $.ajax({
        method: "POST",
        datatype: "json",
        async: false,
        url: "/Proyectos/GetIndexTable",
    }).success(function (data) {
        $('#selectedtable').val(data.Index);
    });
}

</script>

MVCBase/Views/Proyectos/DropdownListTables.cshtml
<label class="col-md-12" for="file">Tablas</label>
@Html.DropDownList("selectedTable", (ViewBag.tables as SelectList), new { @class = "form-control input col-md-12", id = "selectedtable" })

MVCBase/Views/Proyectos/ExecuteAnySqlQueryAgainstDatabase.cshtml
@{
    ViewBag.Title = "ExecuteAnySqlQueryAgainstDatabase";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inserte una Sentencia SQL</h2>

@using (Html.BeginForm())
{

    <textarea name="query" rows="20"cols="50" class="col-md-10 form-control input"></textarea>
    <br/>
    <input type="submit" class="btn btn-primary" value="Ejecutar"/>

}

MVCBase/Views/Proyectos/FieldsMatch.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Carga de Archivos</h2>

@using (Html.BeginForm("InsertRecords", "Proyectos", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Migración de Excel a Base de Datos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="contentpanel">
            <div class="mb15"></div>
            <div class="row">
                <div class="col-md-10">
                    @*<h4 class="panel-title mb5">Emphasize Step Wizard</h4>
                    <p class="mb15">An emphasized step style wizard that is perfect for e-commerce websites.</p>*@  

                        @*<div id="wizard-basic2" class="wizard-style2 wizard clearfix" role="application">
                            <div class="steps clearfix">
                                <ul role="tablist"><li role="tab" class="first done" aria-disabled="false" aria-selected="false"><a id="wizard-basic2-t-0" href="#wizard-basic2-h-0" aria-controls="wizard-basic2-p-0"><span class="number">1.</span> Personal Details <small>Enter your personal information.</small></a></li><li role="tab" class="done" aria-disabled="false" aria-selected="false"><a id="wizard-basic2-t-1" href="#wizard-basic2-h-1" aria-controls="wizard-basic2-p-1"><span class="number">2.</span> Shipping Details <small>Choose your shipping options.</small></a></li><li role="tab" class="last current" aria-disabled="false" aria-selected="true"><a id="wizard-basic2-t-2" href="#wizard-basic2-h-2" aria-controls="wizard-basic2-p-2"><span class="current-info audible">current step: </span><span class="number">3.</span> Payment Details <small>Enter your card information.</small></a></li></ul>
                            </div>
                            <div class="content clearfix">
                                <h3 id="wizard-basic2-h-0" tabindex="-1" class="title">
                                    Carga de Archivo <small>Suba el archivo de Excel.</small>
                                </h3>
                                <div id="wizard-basic2-p-0" role="tabpanel" aria-labelledby="wizard-basic2-h-0" class="body" aria-hidden="true" style="left: -904px; display: none;">
                                    <div class="col-md-4">
                                        <label class="col-md-2" for="file[0]">Archivo</label>
                                        <input type="file" class="form-control input col-md-4" name="file[0]" id="file[0]" />
                                    </div>
                                </div>
                                <h3 id="wizard-basic2-h-1" tabindex="-1" class="title">
                                    Shipping Details <small>Choose your shipping options.</small>
                                </h3>
                                <div id="wizard-basic2-p-1" role="tabpanel" aria-labelledby="wizard-basic2-h-1" class="body" aria-hidden="true" style="display: none; left: -904px;">
                                    <p>Wonderful transition effects.</p>
                                </div>
                                <h3 id="wizard-basic2-h-2" tabindex="-1" class="title current">
                                    Payment Details <small>Enter your card information.</small>
                                </h3>
                                <div id="wizard-basic2-p-2" role="tabpanel" aria-labelledby="wizard-basic2-h-2" class="body current" aria-hidden="false" style="display: block; left: 0px;">
                                    <p>The next and previous buttons help you to navigate through your content.</p>
                                </div>
                            </div>
                            <div class="actions clearfix">
                                <ul role="menu" aria-label="Pagination"><li class="" aria-disabled="false"><a href="#previous" role="menuitem">Previous</a></li><li aria-hidden="true" aria-disabled="true" class="disabled" style="display: none;"><a href="#next" role="menuitem">Next</a></li><li aria-hidden="false" style="display: block;"><a href="#finish" role="menuitem">Finish</a></li></ul>
                            </div>
                        </div>*@
           
                </div>
            </div>
        </div>
        <div class="col-md-12">
        <div class="panel panel-inverse" id="wid-id-5" data-currentnbr="0" data-currentfranja="0">            
                <div class="panel-heading">
                    <h3 class="panel-title">Subida de Archivo</h3>
                </div>
                <div class="panel-body" style="padding-left: 2px; padding-right: 2px;">

                @{
                    <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">

                        <thead>                   
                        <tr>
                            <th class="col-md-6">Campos de la Tabla</th>
                            <th class="col-md-6">Columnas de Excel</th>
                        </tr>
                        </thead>
                        </table>

                        int i = 0;
                        <input type="hidden" name="pair[Index][Index]" />
                        foreach (var field in (ViewBag.fieldsTable as SelectList))
                        {
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.DropDownList("pair[" + i + "][0]", (ViewBag.fieldsTable as SelectList), new { @class = "form-control input col-md-12" })
                                </div>
                                <div class="col-md-6">
                                    @Html.DropDownList("pair[" + i + "][1]", (ViewBag.fieldsExcel as SelectList), new { @class = "form-control input col-md-12" })
                                </div>
                            </div>
                            i++;
                        }

                    }

                </div>
                <div class="panel-footer">
                    <input type="submit" class="btn btn-primary" />
                </div>            
            </div><!-- panel -->
        </div><!-- col-sm-6 -->
    </div>

}

<script type="text/javascript">

        function showMessage(message, color) {
            $.gritter.add({
                title: "Municipalidad de San Pedro Sula",
                text: message,
                class_name: "with-icon exclamation-circle warning"
            });
        }


document.addEventListener('DOMContentLoaded', function () {

  'use strict';
    
  $('#wizard-basic2').steps({    
    headerTag: 'h3',
    bodyTag: 'div',
    transitionEffect: 'slideLeft',
    autoFocus: true
  });

  //var form = $('#wizard-form');
  //form.steps({
  //  headerTag: 'h3',
  //  bodyTag: 'div',
  //  transitionEffect: 'slideLeft',
  //  onStepChanging: function (event, currentIndex, newIndex) {

  //    // Allways allow previous action even if the current form is not valid!
  //    if (currentIndex > newIndex) { return true; }

  //    // Needed in some cases if the user went back (clean up)
  //    if (currentIndex < newIndex) {
  //      // To remove error styles
  //      form.find('.body:eq(' + newIndex + ') label.error').remove();
  //      form.find('.body:eq(' + newIndex + ') .error').removeClass('error');
  //    }

  //    form.validate().settings.ignore = ':disabled,:hidden';
  //    return form.valid();
  //  },
  //  onFinishing: function (event, currentIndex) {
  //    form.validate().settings.ignore = ':disabled';
  //    return form.valid();
  //  },
  //  onFinished: function (event, currentIndex) {
  //    alert('Submitted!');
  //  }
  //}).validate({
  //  highlight: function(element) {
  //    $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
  //  },
  //  success: function(element) {
  //    $(element).closest('.form-group').removeClass('has-error');
  //  }
  //});

});

</script>

MVCBase/Views/Proyectos/FieldsMatchDefaults.cshtml
@using MVCBase.Controllers
@model MVCBase.Files
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Carga de Archivos</h2>

@using (Html.BeginForm("InsertRecords", "Proyectos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Migración de Excel a Base de Datos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="contentpanel">
            <div class="mb15"></div>
            <div class="row">
                <div class="col-md-10">

                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="panel panel-inverse" id="wid-id-5" data-currentnbr="0" data-currentfranja="0">
                <div class="panel-heading">
                    <h3 class="panel-title">Subida de Archivo</h3>
                </div>
                <div class="panel-body" style="padding-left: 2px; padding-right: 2px;">

                    @{
                        <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">

                            <thead>
                                <tr>
                                    <th class="col-md-6">Campos de la Tabla</th>
                                    <th class="col-md-6">Columnas de Excel</th>
                                </tr>
                            </thead>
                        </table>

                        int i = 0;
                        <input type="hidden" name="pair[Index][Index]" />
                        foreach (var field in Model.Fields)
                        {
                            SelectList selectListTabla = null;
                            List<Item> tablaItems = Session["fieldsTable"] as List<Item>;
                            tablaItems.Insert(0, new Item() { Index = -1, Name = "Ignorar" });
                            List<Item> fileItems = Session["fieldsExcel"] as List<Item>;
                            fileItems.Insert(0, new Item() { Index = -1, Name = "Ignorar" });
                            int indexTable = tablaItems.FirstOrDefault(x => x.Name == field.FieldTable).Index;
                            selectListTabla = new SelectList(tablaItems, "Index", "Name", indexTable);
                            SelectList selectListExcel = null;
                            int indexFile = fileItems.FirstOrDefault(x => x.Name == field.FieldFile).Index;
                            selectListExcel = new SelectList(fileItems, "Index", "Name", indexFile);
                            <div class="row">
                                <div class="col-md-6">
                                    @Html.DropDownList("pair[" + i + "][0]", selectListTabla, new { @class = "form-control input col-md-12" })
                                </div>
                                <div class="col-md-6">
                                    @Html.DropDownList("pair[" + i + "][1]", selectListExcel, new { @class = "form-control input col-md-12" })
                                </div>
                            </div>
                            i++;
                        }

                    }

                </div>
                <div class="panel-footer">
                    <input type="submit" class="btn btn-primary" />
                </div>
            </div><!-- panel -->
        </div><!-- col-sm-6 -->
    </div>

                        }

<script type="text/javascript">

        function showMessage(message, color) {
            $.gritter.add({
                title: "Municipalidad de San Pedro Sula",
                text: message,
                class_name: "with-icon exclamation-circle warning"
            });
        }


document.addEventListener('DOMContentLoaded', function () {

  'use strict';

  $('#wizard-basic2').steps({
    headerTag: 'h3',
    bodyTag: 'div',
    transitionEffect: 'slideLeft',
    autoFocus: true
  });

});

</script>

MVCBase/Views/Proyectos/ValoresPerFactor.cshtml
@using MVCBase.Models

<label for="valores" class="control-label">Valor</label>
@Html.DropDownList("valores", null, htmlAttributes: new { @class = "form-control", id = "valores" })